codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "75...90"

  status:
    project: yes
    patch: yes
    changes: no

ignore:
  - "api/src/main/java/org/openmrs/module/fhir2/FhirActivator.java"
  - "api/src/main/java/org/openmrs/module/fhir2/FhirConstants.java"
  - "api/src/main/java/org/openmrs/module/fhir2/model/**/*.java"
  - "api/src/main/java/org/openmrs/module/fhir2/providers/util/TaskVersionConverter.java"
  - "omod/src/main/java/org/openmrs/module/fhir2/web/filter/AuthenticationFilter.java"
  - "omod/src/main/java/org/openmrs/module/fhir2/web/filter/ForwardingFilter.java"
